eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-note-ms:
      path: /vue-note/**
      url: http://localhost:8800/
    api-novel-ms:
      path: /vue-novel/**
      url: http://localhost:8801/
